### ISSUE TITLE
The toolbar is still ugly

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#100]
(╯°□°)╯︵ ┻━┻

We should work out a slightly less innovative design

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3298404/192108001-9ae191dd-7faf-499c-a3b0-7293e3416128.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3298404/192108017-35d0b9fa-5e2d-484f-9b68-d965ce1ca29e.png">

**Comment by silverv** [comment]
Let Zen do it

**Comment by silverv** [comment]
In its entirety, coding included
