### ISSUE TITLE
The application process is not stopped after the main window is closed

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#101]
Steps to reproduce:

- Download the GNU/Linux binary and run it
- Connect to a CAN network (e.g., via Babel)
- Exit the application

The process will keep running but the window is gone. There appear no new log messages when the window is closed.

**Comment by silverv** [comment]
This is a very significant problem and I think I will solve it by looking for when the polling of the backend ends, then stopping the backend.
