### ISSUE TITLE
Display a splash screen during application initialization

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#102]
Unpacking & initialization takes a few seconds, it is best to show a splash screen to avoid misunderstanding.

**Comment by silverv** [comment]
Pyinstaller supports this, it would be nice indeed

**Comment by silverv** [comment]
This is very unlikely to be done, I tried but the feature of Pyinstaller is too experimental and I didn't manage to get a working executable with Splash configured on neither Linux or Win

**Comment by silverv** [comment]
But I do consider this an important part in making using Yukon as smooth as possible
