### ISSUE TITLE
Some registers fail to load

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#106]
This is obtained with a Myxa:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/3298404/192108808-c62d4d21-a8c6-4613-af54-aa6df8b14521.png">

Clicking "reread node registers" does not help. I think this button neglects to re-read the register list.

If the node is physically disconnected/reconnected, the set of missing registes would be different.

**Comment by silverv** [comment]
Which registers are missing, how do I reproduce if I don't know how to detect the bug?

**Comment by silverv** [comment]
Haven't been able to reproduce so far because the required utilities (setup_slcan and .env_slcan) are broken and there is no other reliable method of communication to CAN devices than SLCAN over SocketCAN

**Comment by silverv** [comment]
I believe this is solved
