### ISSUE TITLE
Flask (and Yukon) will take MIME type values from Win 10 registry

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#116]
This will mean that Yukon fails to present anything in the front end if the user has installed a text editor or anything else that modifies the registry, the correct solution as pointed out here is to override the registry, not sure how to do that yet. Also this is detectable so I am considering adding a detection and telling the user about this. Maybe even offer to fix this in the registry?
https://github.com/golang/go/issues/32350
![image](https://user-images.githubusercontent.com/15844364/192818684-a3970e16-57f3-4c03-a279-9d23fbd8ee44.png)

**Comment by silverv** [comment]
The image shows that registry on this Win 10 machine has been modified such that .js files no longer have the MIME type which is needed for the .js file to be usable on a loaded webpage. The browser will refuse to load scripts that have incorrect MIME types.

**Comment by silverv** [comment]
In this case it's possible to just erase the two keys: Content Type and PerceivedType for Cimputer\HKEY_CLASSES_ROOT\..js

**Comment by silverv** [comment]
No, this is Flask/Windows specific, Electron is affected too

**Comment by silverv** [comment]
This will affect builds too

**Comment by pavel-kirienko** [comment]
But can't you override the MIME type when serving requests in Flask?

**Comment by silverv** [comment]
Just tried, it doesn't work on Windows

**Comment by silverv** [comment]
```
def make_landing_and_bridge(state: GodState, api: Api) -> None:
    @server.route("/<path:path>", methods=["GET"])
    def any_file(path: str) -> typing.Any:
        with open(os.path.join(gui_dir, path), "rb") as f:
            if ".js" in path:
                print("Found a javascript file")
                response = Response(f.read(), mimetype="application/javascript")
                response.headers["Content-Type"] = "text/xml; charset=utf-8"
                return response
            else:
                print("Found a normal file")
                return Response(f.read())
```
