### ISSUE TITLE
Add global register view

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#14]
https://forum.opencyphal.org/t/yukon-design-megathread/390/25?u=pavel.kirienko

**Comment by pavel-kirienko** [comment]
Important use cases:

- [ ] export one node
- [ ] export all nodes (or a selected set of nodes)
- [ ] import one node
- [ ] import a set of nodes
- [ ] always display register metadata: mutable/immutable; persistent/volatile; data type name (`string`, `uint8[]`, etc.).
  :warning: Warning :skull_and_crossbones:: the metadata is defined per cell, not per row, so a slightly richer view may be needed.
- [ ] assign (same) value to a register or a group of registers
- [ ] assign (same) value to a row (useful when tuning motor controllers)
- [ ] an easy-to-reach button or a shortcut for refreshing a register

Less important use cases (optional):

- [ ] highlight cell on data change (like Yakut monitor, or like variable views in IDEs from JetBrains)

**Comment by silverv** [comment]
Refresh means reread from devices
