### ISSUE TITLE
The caret icon for accordions should include a gear icon or be one

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#155]
This is for first time users so it's more discoverable
![Screenshot_20221007_194659](https://user-images.githubusercontent.com/15844364/194605691-a0f06b5e-5948-4ecd-9d30-cb534f32da09.png)

**Comment by pavel-kirienko** [comment]
![image](https://user-images.githubusercontent.com/3298404/194606296-e989e5f4-65d5-4f3c-8a9a-3e51ad9f4232.png)
