### ISSUE TITLE
Why did my development machine have three instances of demos running when it booted up visual studio code?

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#164]

**Comment by silverv** [comment]
This might come as a surprise for anyone who wants to develop Yukon in the future

**Comment by pavel-kirienko** [comment]
Is this a trick question?

![image](https://user-images.githubusercontent.com/3298404/195099987-2a8d913e-d141-4ae9-93db-7554d1edec0b.png)

**Comment by silverv** [comment]
This can also make tests succeed even when the test failed to launch Yukon

**Comment by silverv** [comment]
2 PyCyphal demos were also running

**Comment by silverv** [comment]
Debugged using this: https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer, it shows where processes originate from and what tree they belong to.

**Comment by silverv** [comment]
My tests were being run when vscode opened during test discovery
