### ISSUE TITLE
Rename the application

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#17]
Looking at the direction this project is going and considering the last OpenCyphal call, I wonder if we should consider renaming this project into Yukon, thereby effectively replacing the original Yukon project with what is now known as KucherX? The main reason why it is likely to be beneficial is that we've inadvertently created some hype around Yukon in the past but failed to deliver due to our [inability to recruit resources and developers](https://docs.google.com/presentation/d/1gy5Iv4ymX-FmjuYCFX_0h-iGEUCdmULX/edit#slide=id.p10). Now, KucherX is actually a very decent approximation of what was promised for Yukon, so merely switching the label might allow us to achieve two goals at once: 1. fulfill the promise of a decent open-source OpenCyphal tool; 2. increase the chances of receiving contributions from third-party developers.

This will necessitate the removal of the GPL encumbrance, so PyQt will have to go. I understood that this is not a major hurdle.

**Comment by pavel-kirienko** [comment]
Done

**Comment by pavel-kirienko** [comment]
Closed too soon. The app itself is not yet renamed.

**Comment by silverv** [comment]
Done with 2fb4a7f
