### ISSUE TITLE
Incomplete port name visualization on the Monitor window

### ISSUE THREAD

**Issue by PonomarevDA** [OpenCyphal-Garage/yukon#296]
I'm using Yukon for PX4 and Ardupilot. I've added `port.List` on my custom branch and found out that some of their port names are incompletely visualized in the Monitor window.

Let's study PX4. All port related registers have the following name pattern: `uavcan.<pub/sub>.<udral/uorb>.<port name>.<instance number>.id`. For example, the ESC related register name is `uavcan.pub.udral.esc.0.id`. You can check the actual registers names in [ParamManager.hpp](https://github.com/PX4/PX4-Autopilot/blob/main/src/drivers/cyphal/ParamManager.hpp#L119).

All register names are correctly parsed in the Registers window:
![image](https://user-images.githubusercontent.com/36133264/217386123-25413b9a-3cb3-425f-beb6-67f812a821dd.png)

In the Monitor window I expect to see `uadral.esc.0` . But I see just their instance numbers:
![image](https://user-images.githubusercontent.com/36133264/217385724-979d1f3a-1ae0-4a77-aedb-6b27811da95f.png)

All ports which have no dot in their name, it is fine.

Should this problem be solved on the autopilot side by changing the port name pattern (for example by using underscore instead of dots), or can Yukon handle such names?

Thanks.

**Comment by silverv** [comment]
I programmed it in a way that expects the last element separated by dot to be id, the second last to be the link name and the third last to be the port type (pub/sub/cln/srv).

**Comment by pavel-kirienko** [comment]
That is, strictly speaking, up to spec, but then the spec is incorrect:

https://github.com/OpenCyphal/public_regulated_data_types/blob/70573cb98a346f5a9aee54ce421a8a79700df2b4/uavcan/register/384.Access.1.0.dsdl#L128-L139

I think it should be updated to allow the full stop symbol inside the PORT_NAME.

**Comment by silverv** [comment]
Yes, I will do this.

**Comment by PonomarevDA** [comment]
Thanks! With the latest release it works well.
 
![image](https://user-images.githubusercontent.com/36133264/219111392-4fff9969-bfda-4086-88aa-625cfede3c23.png)
