### ISSUE TITLE
It should be possible to hide the select row and select column buttons

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#37]
Experienced users would benefit because you can already click on  the cell containing these buttons and it has the same effect, just less clutter and more space on the screen.

**Comment by pavel-kirienko** [comment]
They should not be shown at all. Selecting row/column by clicking on the header is a common UX choice that everyone is familiar with.

**Comment by silverv** [comment]
It's now a setting (although in code)
