### ISSUE TITLE
It should be possible to freeze row headers

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#38]
For use with large networks, it would make it easier to understand what the name of the register is. Although this is already implemented using a tooltip.

**Comment by pavel-kirienko** [comment]
I think they should be just frozen always, no? The same should apply to the column headers (that is, node-IDs).

**Comment by silverv** [comment]
Fixed, always frozen + hovered row is highlighted to make the user super confident that they are looking at the right register.
DONE
