### ISSUE TITLE
Only a part of the registers may load

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#45]
![image](https://user-images.githubusercontent.com/15844364/188078127-c2cad8ef-9b14-4ffd-a656-6a9b6df66e45.png)

**Comment by silverv** [comment]
Reread doesn't help

**Comment by silverv** [comment]
This issue is caused by the backend not correctly fetching registers of nodes that have appeared on the network. Maybe it is because nobody is sending them a getinfo request after their startup process is finished or the getinfo request is sent earlier.

**Comment by silverv** [comment]
Tried to fix it by adding 
```
    if len(register_values.keys()) == 0:

        async def get_register_names_after_delay():
            await asyncio.sleep(1)
            await get_register_names(state, node_id, new_avatar)

        asyncio.create_task(get_register_names_after_delay())
```
to get_register_names in snoop_registers.py but to no avail

**Comment by pavel-kirienko** [comment]
The network may lose any request for whatever reason and you need to be prepared for that. Adding a delay is not a viable fix. You need to retry every few seconds until you get a response.
