### ISSUE TITLE
Work out a new widget organization that does not suck

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#51]
We know that the current tab-based organization is a mere placeholder. As the development is progressing, we need to work out a new way to organize different widgets such that the application is actually usable. One idea is to use dockable windows for less important stuff (such as transport configuration) while keeping the most important things in the background (like the Register View or the Network Graph).

**Comment by silverv** [comment]
I see no usability issues with the current tab based layout but I can agree that it's not the most customizable and that's why we're changing it.

**Comment by silverv** [comment]
You are being over-dramatic and it's surprising.

**Comment by pavel-kirienko** [comment]
<img src="https://user-images.githubusercontent.com/3298404/188222113-8758f905-3af6-4430-9509-b05fc196369c.jpg" width="256">
