### ISSUE TITLE
Editing the values of multiple registers at the same time

### ISSUE THREAD

**Issue by silverv** [OpenCyphal-Garage/yukon#55]
Even for registers with different datatypes, this should be possible
![image](https://user-images.githubusercontent.com/15844364/188465819-6a5b0d49-bb5d-4be6-9b14-ffdefdbcf735.png)

**Comment by pavel-kirienko** [comment]
In the backend you can check if the given string is coercible to the target data type (this is implemented in pycyphal.application.register)

**Comment by silverv** [comment]
This was implemented
