### ISSUE TITLE
Incorrect input not validated / mishandled

### ISSUE THREAD

**Issue by pavel-kirienko** [OpenCyphal-Garage/yukon#99]
Enter an invalid node-ID and start the transport. The correct behavior is to display an error message. The actual behavior is that nothing appears to happen.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/3298404/192107866-e54892fb-cfbe-44fb-b5aa-e6a3a00d239c.png">

**Comment by pavel-kirienko** [comment]
Same problem if the port is not accessible due to lack of permissions.

**Comment by silverv** [comment]
![image](https://user-images.githubusercontent.com/15844364/192517826-46a39c53-6914-4552-b655-8fcca75f40ca.png)
This seems solved, I hope you agree
@pavel-kirienko 
![image](https://user-images.githubusercontent.com/15844364/192517916-2f849a8a-3903-4417-8079-767352736abc.png)
![image](https://user-images.githubusercontent.com/15844364/192518014-b80ce3fb-82f0-40df-87a0-bab82448367a.png)

**Comment by pavel-kirienko** [comment]
Nice. Let us please only record the stack trace in the messages view; the UI element shown on the screenshot should only contain the error message, that is, `str(ex) or repr(ex)`.

The last error message appears misformatted.
